### ISSUE TITLE
Partnerlogos

### ISSUE THREAD

**Issue by ghost** [metacollectde/landingpage#10]
Logos aus dem Vortrag zum Netzwerk hinzufügen.

**Comment by almereyda** [comment]
Dieses Issue könnte nach _Partnerlogos_ umbenannt werden, da es ansonsten mit #8 zu verwechseln ist.

**Comment by rhotep** [comment]
Welche Logos sind das denn und wo finde ich die? :)
Zurzeit sind die Logos unter Netzwerk nicht verlinkt. Würd eich noch ergäzem, wenn mir jemand die Links gibt und das erwünscht ist.

**Comment by Midnighter** [comment]
Hier findest du die Logos: [netzwerkpartner.zip](https://github.com/metacollect-org/landingpage/files/190561/netzwerkpartner.zip)

http://www.migrationhub.eu/
http://www.betterplace-lab.org/
http://codefor.de/
http://ini20.de/
https://www.useeds.de/
http://socialprohub.org/
http://prosper.community/
http://techfugees.com/

**Comment by Midnighter** [comment]
Muss dann in Zukunft erweitert werden.
