### ISSUE TITLE
Mobile version - Text teilweise nicht sichtbar

### ISSUE THREAD

**Issue by dataista** [metacollectde/landingpage#12]
Die oberste Zeile von "metacollect ist ein Open Data Service, der aktuelle Informationen über zivilgesellschaftliche Projekte sammelt und bereitstellt." ist in der mobile Version auf dem ersten Blick nicht sichtbar. 
Anscheinend verdeckt das Menü diese Zeile. Können wir ein Sandwich-Menü für die mobile Version haben? Das sollte das Problem lösen.

**Comment by rhotep** [comment]
Gibt jetzt einen Menu button :)

**Comment by dataista** [comment]
Auf meinem ipad ist die oberste Zeile von "metacollect ist ein Open Data Service, der aktuelle Informationen über zivilgesellschaftliche Projekte sammelt und bereitstellt." immer noch nicht sichtbar. Wir siehts denn auf nem Smartphone aus? (hab keins zur Hand, kann es also leider nicht testen)

**Comment by willi84** [comment]
![screenshot_2016-03-11-09-16-39](https://cloud.githubusercontent.com/assets/6207308/13696960/61cad164-e76a-11e5-8669-a8af469b4080.png)

Samsung Galaxy S5

**Comment by rhotep** [comment]
Die akuelle Version im Repo sollte diesen Fehler nicht mehr haben. Die schient aber gerade nicht deployed zu sein.
Was gerade hier liegt: http://dsini20.schedar.uberspace.de/landingpage/#/home ist nicht die aktuelle Version im Repo. Im Zweifel einmal pullen und lokal testen,

**Comment by Midnighter** [comment]
> Im Zweifel einmal pullen und lokal testen

Habe ich mal gemacht. Sieht gut aus und ist auch jetzt deployed. @willi84, @dataista könnt ihr das bestätigen?

**Comment by Midnighter** [comment]
Schließe das erst mal, könnt euch ja melden, falls es wieder auftaucht.
