### ISSUE TITLE
Schnittstelle (API)

### ISSUE THREAD

**Issue by almereyda** [metacollectde/landingpage#16]
Im Schnittstellenabschnitt gibt es einen [schlecht sichtbaren Link](https://hypothes.is/a/AVN2ckXMH9ZO4OKSlOEt).

**Comment by dataista** [comment]
Vorschlag: Links werden unterstrichen (sollte auch ins Designkonzept passen).

**Comment by rhotep** [comment]
Da ist doch gar kein link... wait a second.

**Comment by rhotep** [comment]
Links sind jetzt alle unterstrichen und haben keine Hover-Effekt mehr (blau werden auf blauen Hintergrund war auch nicht so gut :P)

**Comment by Midnighter** [comment]
Danke für die Lösung. Britta denkt auch noch mal darüber nach. Als hover könnte noch bold sinnvoll sein, aber ich würde jetzt mal kurz warten.

**Comment by rhotep** [comment]
`<em></em>` wird derzeit unterstichten und sieht grade aus wie ein link. Vorschlag in der Sprachdatei `<em>` durch `<strong>` ersetzen.

**Comment by Midnighter** [comment]
Hab ich mal gemacht.
