### ISSUE TITLE
Suchfeld - Formatierung funktioniert nur teilweise

### ISSUE THREAD

**Issue by dataista** [metacollectde/landingpage#3]
Das Suchfeld wird nicht richtig angezeigt, zumindest nicht bei einem großen Fenster (getestet auf Firefox 44.0.2, siehe Screenshot - leider mit paint gemacht)
![screenshot_20160303](https://cloud.githubusercontent.com/assets/7595339/13512805/326dcb38-e19d-11e5-8e99-8e621e6af419.jpg)

Wenn ich das Fenster allerdings verkleinere, haut auch irgendwann die Formatierung des Suchfelds hin.

**Comment by rhotep** [comment]
Sollte jetzt klappen :)

**Comment by ghost** [comment]
Bei mir läuft's.
