### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by ghost** [metacollectde/landingpage#6]
- [x] Die Reihenfolge im Menu stimmt Englisch/Deutsch noch nicht überein.
- [ ] Es fehlen noch neue Menueinträge für die neuen Abschnitte

**Comment by rhotep** [comment]
Wenn Die Reihenfolge nicht stimmt, stimmt was in derLangugae file nicht.
Ansonstne bitte mal sagen welche link in wlecher Reihenfolge in den Header sollen :)

**Comment by dataista** [comment]
Wenn wir alle Abschnitte ins Menü packen, dann wird das Menü zu groß. Wir werden das noch einmal kurz im Team besprechen ( @metacollectorg ).

**Comment by dataista** [comment]
Wichtiger als die weiteren Menüpunkte ist allerdings ein anderer Link in der Menüleiste - "Anmelden". Ich möchte diesen Punkt zwischen "Kontakt" und "DE/EN" einschieben und unterstreichen. Auf dem Text "Anmelden" sollte folgender Link hinterlegt sein: http://django.dsini20.schedar.uberspace.de/mainApp/accounts/login/ 

Ohne diese Anmeldemöglichkeit fehlt eine wesentliche Komponente der derzeitigen metacollect-Präsenz. Projekte können sich derzeit nur anmelden bzw. gar registrieren, wenn sie ihr Projekt gefunden haben und auf den Titel geklickt haben. Projekte ohne Eintrag können sich derzeit nicht anmelden (bzw. nur auf wirre Umwege).

Falls es in der Menüleiste zu eng wird, dann können wir zunächst "Team" herausnehmen. Wie erwähnt: Für die Menüleiste müssten wir uns eh noch etwas einfallen lassen.

**Comment by almereyda** [comment]
Die Reihenfolge von [Vision](https://hypothes.is/a/AVN2cdjnH9ZO4OKSlOEl) und [Interaktion](https://hypothes.is/a/AVN2cfb-H9ZO4OKSlOEo) ist im Vergleich zur vertikalen Hierarchie der respektiven Blöcke auf der Seite anders.

**Comment by rhotep** [comment]
Hab die Reihenfolge im Menu angepasst und einen Anmeldelink eingefügt.
